# Generated by Django 6.0.5 on 2026-05-28 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.category')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('expense', 'Расход'), ('income', 'Доход'), ('transfer', 'Перевод')], default='expense', max_length=10)),
                ('currency_code', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов'), ('CHF', 'Швейцарский франк'), ('JPY', 'Японская иена'), ('CNY', 'Китайский юань'), ('KZT', 'Тенге'), ('BYN', 'Белорусский рубль'), ('INR', 'Индийская рупия'), ('AED', 'Дирхам ОАЭ'), ('SGD', 'Сингапурский доллар'), ('other', 'Другая')], default='RUB', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('note', models.TextField(blank=True, verbose_name='Описание')),
                ('operation_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_time', models.TimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='finance.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='finance.service')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_tags', to='finance.operation')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_tags', to='finance.tag')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов'), ('CHF', 'Швейцарский франк'), ('JPY', 'Японская иена'), ('CNY', 'Китайский юань'), ('KZT', 'Тенге'), ('BYN', 'Белорусский рубль'), ('INR', 'Индийская рупия'), ('AED', 'Дирхам ОАЭ'), ('SGD', 'Сингапурский доллар'), ('other', 'Другая')], default='RUB', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('custom_name', models.CharField(blank=True, max_length=24, verbose_name='Произвольное наименование')),
                ('payment_interval_months', models.PositiveSmallIntegerField(default=1)),
                ('payment_day', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('debit_card', 'Дебетовая карта'), ('credit_card', 'Кредитная карта'), ('deposit', 'Вклад'), ('savings_account', 'Накопительный счёт'), ('brokerage_account', 'Брокерский счёт'), ('iis', 'ИИС'), ('investment_piggy_bank', 'Инвесткопилка'), ('metal_account', 'Металлический счёт'), ('loan', 'Кредит/займ')], default='debit_card', max_length=30)),
                ('bank_name', models.CharField(choices=[('sber', 'Сбербанк'), ('vtb', 'ВТБ'), ('alfa', 'Альфа-Банк'), ('t_bank', 'Т-Банк'), ('gazprom', 'Газпромбанк'), ('rshb', 'Россельхозбанк'), ('sovcom', 'Совкомбанк'), ('psb', 'ПСБ'), ('yandex', 'Яндекс'), ('ozon', 'Ozon'), ('wildberries', 'Wildberries'), ('other', 'Другой')], default='other', max_length=30)),
                ('currency_code', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро'), ('GBP', 'Фунт стерлингов'), ('CHF', 'Швейцарский франк'), ('JPY', 'Японская иена'), ('CNY', 'Китайский юань'), ('KZT', 'Тенге'), ('BYN', 'Белорусский рубль'), ('INR', 'Индийская рупия'), ('AED', 'Дирхам ОАЭ'), ('SGD', 'Сингапурский доллар'), ('other', 'Другая')], default='RUB', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('custom_name', models.CharField(blank=True, max_length=24, verbose_name='Произвольное наименование')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'product_type'], name='finance_fin_user_id_25b613_idx'), models.Index(fields=['bank_name'], name='finance_fin_bank_na_2448ec_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['user', 'operation_date'], name='finance_ope_user_id_fa2cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['operation_type'], name='finance_ope_operati_e6dca5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='operationtag',
            unique_together={('operation', 'tag')},
        ),
        migrations.AddIndex(
            model_name='upcomingpayment',
            index=models.Index(fields=['user', 'payment_day'], name='finance_upc_user_id_037c84_idx'),
        ),
        migrations.AddIndex(
            model_name='upcomingpayment',
            index=models.Index(fields=['service'], name='finance_upc_service_7892fc_idx'),
        ),
    ]
