# Generated by Django 6.0.5 on 2026-05-28 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialproduct',
            name='serial_number',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Последние 4 цифры / код продукта'),
        ),
        migrations.AddField(
            model_name='operation',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.financialproduct'),
        ),
        migrations.AddField(
            model_name='upcomingpayment',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.financialproduct'),
        ),
    ]
